version: "3"
name: WSL
services:
  db:
    image: mongo
    restart: always
    # environment:
    #   POSTGRES_PASSWORD: admin123
    #   POSTGRES_USER: postgres
    #   POSTGRES_DB: task
    ports:
      - "27017:27017"
    networks:
      - webnet
  web:
    image: sharooque11/dashboardapp
    ports:
      - "3000:3000"
    networks:
      - webnet
    environment:
      REACT_APP_API_URL: http://localhost:4000/
  backend:
    image: sharooque11/dashnodeapp
    ports:
      - "4000:4000"
    networks:
      - webnet
    depends_on:
      - db
    environment:
      MONGODB_URL: mongodb://localhost:27017/skills
      PORT: 4000
      NODE_ENV: development
      JWT_SECRET: WSLSECRET
networks:
  webnet:
